<#
.SYNOPSIS
Safely cleans temporary files on Windows endpoints with dry-run and rollback support.

.DESCRIPTION
This script targets temporary file locations, filters files by age, and moves files to a
staging folder so they can be restored later. It supports dry-run mode, per-file error
handling, locked-file detection, timestamped logging, and end-of-run summaries.

.NOTES
Designed for Windows PowerShell 5.1.
#>

[CmdletBinding()]
param(
    # One or more folders to scan for temp files.
    [Parameter(Mandatory = $false)]
    [string[]]$Paths = @($env:TEMP, (Join-Path $env:WINDIR 'Temp')),

    # Only files older than this many days are targeted. Default 0 means all files older than "now".
    [Parameter(Mandatory = $false)]
    [ValidateRange(0, 36500)]
    [int]$OlderThanDays = 0,

    # Shows files that would be removed without changing anything.
    [Parameter(Mandatory = $false)]
    [switch]$DryRun,

    # Restores files from a prior run by reading its manifest file.
    [Parameter(Mandatory = $false)]
    [switch]$Rollback,

    # Path to a manifest CSV created by a previous cleanup run.
    [Parameter(Mandatory = $false)]
    [string]$ManifestPath,

    # Folder where log files are written.
    [Parameter(Mandatory = $false)]
    [string]$LogRoot,

    # Folder used to stage files before final deletion policy is decided.
    [Parameter(Mandatory = $false)]
    [string]$StagingRoot = (Join-Path $env:ProgramData 'DWPTempCleanup\Staging')
)

# Section: Applies runtime defaults for paths that depend on script location.
if ([string]::IsNullOrWhiteSpace($LogRoot)) {
    $scriptDirectory = Split-Path -Path $MyInvocation.MyCommand.Path -Parent
    $LogRoot = Join-Path $scriptDirectory 'logs'
}

# Section: Initialize runtime context and log file paths.
$timestamp = Get-Date -Format 'yyyyMMdd_HHmmss'
$runId = '{0}_{1}' -f $timestamp, ([Guid]::NewGuid().ToString('N').Substring(0, 8))
$logPrefix = if ($Rollback) { 'rollback' } else { 'cleanup' }
$logFileName = '{0}_{1}.log' -f $logPrefix, $timestamp

if (-not (Test-Path -LiteralPath $LogRoot)) {
    New-Item -Path $LogRoot -ItemType Directory -Force | Out-Null
}

$logFilePath = Join-Path $LogRoot $logFileName

# Section: Writes a timestamped message to console and log file.
function Write-Log {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Message,

        [Parameter(Mandatory = $false)]
        [ValidateSet('INFO', 'WARN', 'ERROR')]
        [string]$Level = 'INFO'
    )

    $line = '[{0}] [{1}] {2}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $Level, $Message
    Add-Content -LiteralPath $logFilePath -Value $line
    Write-Host $line
}

# Section: Tests whether a file is currently locked by another process.
function Test-FileLocked {
    param(
        [Parameter(Mandatory = $true)]
        [string]$FilePath
    )

    try {
        $stream = [System.IO.File]::Open($FilePath, 'Open', 'ReadWrite', 'None')
        if ($stream) {
            $stream.Close()
            $stream.Dispose()
        }
        return $false
    }
    catch [System.IO.IOException] {
        return $true
    }
    catch {
        # Unknown access issues are not treated as lock; caller will handle the actual move error.
        return $false
    }
}

# Section: Restores files from a manifest generated by a previous cleanup run.
function Invoke-Rollback {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Manifest
    )

    $summary = [ordered]@{
        TotalManifestEntries = 0
        Restored             = 0
        MissingStagedFile    = 0
        DestinationExists    = 0
        Failed               = 0
    }

    if (-not (Test-Path -LiteralPath $Manifest)) {
        Write-Log -Level 'ERROR' -Message ('Manifest not found: {0}' -f $Manifest)
        return $summary
    }

    Write-Log -Message ('Rollback started. Manifest: {0}' -f $Manifest)
    $entries = Import-Csv -LiteralPath $Manifest
    $summary.TotalManifestEntries = $entries.Count

    foreach ($entry in $entries) {
        try {
            $originalPath = $entry.OriginalPath
            $stagedPath = $entry.StagedPath

            if (-not (Test-Path -LiteralPath $stagedPath)) {
                $summary.MissingStagedFile++
                Write-Log -Level 'WARN' -Message ('Staged file missing, skipping: {0}' -f $stagedPath)
                continue
            }

            if (Test-Path -LiteralPath $originalPath) {
                $summary.DestinationExists++
                Write-Log -Level 'WARN' -Message ('Original path already exists, skipping: {0}' -f $originalPath)
                continue
            }

            $destinationDir = Split-Path -Path $originalPath -Parent
            if (-not (Test-Path -LiteralPath $destinationDir)) {
                New-Item -Path $destinationDir -ItemType Directory -Force | Out-Null
            }

            Move-Item -LiteralPath $stagedPath -Destination $originalPath -Force -ErrorAction Stop
            $summary.Restored++
            Write-Log -Message ('Restored: {0}' -f $originalPath)
        }
        catch {
            $summary.Failed++
            Write-Log -Level 'ERROR' -Message ('Rollback failed for {0}. Error: {1}' -f $entry.OriginalPath, $_.Exception.Message)
        }
    }

    Write-Log -Message ('Rollback finished. Restored={0}, MissingStaged={1}, DestinationExists={2}, Failed={3}' -f $summary.Restored, $summary.MissingStagedFile, $summary.DestinationExists, $summary.Failed)

    return $summary
}

# Section: Validates paths and prepares staging folder for cleanup mode.
if (-not (Test-Path -LiteralPath $StagingRoot)) {
    New-Item -Path $StagingRoot -ItemType Directory -Force | Out-Null
}

Write-Log -Message ('Script started. DryRun={0}, Rollback={1}, OlderThanDays={2}' -f $DryRun.IsPresent, $Rollback.IsPresent, $OlderThanDays)
Write-Log -Message ('Log file: {0}' -f $logFilePath)

# Section: Executes rollback flow and exits when -Rollback is set.
if ($Rollback) {
    if ([string]::IsNullOrWhiteSpace($ManifestPath)) {
        $latestManifest = Get-ChildItem -Path $StagingRoot -Recurse -Filter 'manifest_*.csv' -ErrorAction SilentlyContinue |
            Sort-Object LastWriteTime -Descending |
            Select-Object -First 1

        if ($null -eq $latestManifest) {
            Write-Log -Level 'ERROR' -Message 'No manifest was provided and no manifest files were found in staging.'
            exit 1
        }

        $ManifestPath = $latestManifest.FullName
        Write-Log -Message ('Using latest manifest automatically: {0}' -f $ManifestPath)
    }

    $rollbackSummary = Invoke-Rollback -Manifest $ManifestPath

    Write-Host ''
    Write-Host 'Rollback Summary'
    Write-Host '----------------'
    Write-Host ('Manifest entries : {0}' -f $rollbackSummary.TotalManifestEntries)
    Write-Host ('Restored         : {0}' -f $rollbackSummary.Restored)
    Write-Host ('Missing staged   : {0}' -f $rollbackSummary.MissingStagedFile)
    Write-Host ('Destination exists: {0}' -f $rollbackSummary.DestinationExists)
    Write-Host ('Failed           : {0}' -f $rollbackSummary.Failed)
    Write-Host ('Log file         : {0}' -f $logFilePath)

    exit 0
}

# Section: Calculates file age cutoff and initializes counters for summary reporting.
$cutoff = (Get-Date).AddDays(-$OlderThanDays)
$cleanupRunFolder = Join-Path $StagingRoot $runId
$manifestPathForRun = Join-Path $cleanupRunFolder ('manifest_{0}.csv' -f $runId)

if (-not $DryRun) {
    New-Item -Path $cleanupRunFolder -ItemType Directory -Force | Out-Null
}

$summary = [ordered]@{
    TotalScanned  = 0
    CandidateFiles = 0
    MovedToStaging = 0
    LockedSkipped = 0
    Failed        = 0
    DryRunListed  = 0
}

$manifestRows = New-Object System.Collections.Generic.List[object]

Write-Log -Message ('Cutoff date/time: {0}' -f $cutoff)

# Section: Enumerates candidate files from each target path.
foreach ($path in $Paths) {
    if (-not (Test-Path -LiteralPath $path)) {
        Write-Log -Level 'WARN' -Message ('Path not found, skipping: {0}' -f $path)
        continue
    }

    Write-Log -Message ('Scanning path: {0}' -f $path)

    $files = Get-ChildItem -LiteralPath $path -File -Recurse -Force -ErrorAction SilentlyContinue

    foreach ($file in $files) {
        $summary.TotalScanned++

        if ($file.LastWriteTime -ge $cutoff) {
            continue
        }

        $summary.CandidateFiles++

        if ($DryRun) {
            $summary.DryRunListed++
            Write-Log -Message ('DRY-RUN would remove: {0}' -f $file.FullName)
            Write-Host ('[DRY-RUN] {0}' -f $file.FullName)
            continue
        }

        # Section: Per-file processing with try/catch to avoid stopping the script on individual failures.
        try {
            if (Test-FileLocked -FilePath $file.FullName) {
                $summary.LockedSkipped++
                Write-Log -Level 'WARN' -Message ('Locked file skipped: {0}' -f $file.FullName)
                continue
            }

            $stagedFileName = '{0}_{1}{2}' -f [System.IO.Path]::GetFileNameWithoutExtension($file.Name), ([Guid]::NewGuid().ToString('N')), $file.Extension
            $stagedPath = Join-Path $cleanupRunFolder $stagedFileName

            Move-Item -LiteralPath $file.FullName -Destination $stagedPath -Force -ErrorAction Stop

            $manifestRows.Add([PSCustomObject]@{
                RunId         = $runId
                OriginalPath  = $file.FullName
                StagedPath    = $stagedPath
                LastWriteTime = $file.LastWriteTime.ToString('o')
                LengthBytes   = $file.Length
                MovedAt       = (Get-Date).ToString('o')
            }) | Out-Null

            $summary.MovedToStaging++
            Write-Log -Message ('Moved to staging: {0} -> {1}' -f $file.FullName, $stagedPath)
        }
        catch {
            $summary.Failed++
            Write-Log -Level 'ERROR' -Message ('Failed to process file {0}. Error: {1}' -f $file.FullName, $_.Exception.Message)
        }
    }
}

# Section: Persists manifest for rollback and writes final summary.
if (-not $DryRun -and $manifestRows.Count -gt 0) {
    $manifestRows | Export-Csv -LiteralPath $manifestPathForRun -NoTypeInformation
    Write-Log -Message ('Manifest written: {0}' -f $manifestPathForRun)
}
elseif (-not $DryRun -and $manifestRows.Count -eq 0) {
    Write-Log -Message 'No files moved. No manifest created.'
}

Write-Host ''
Write-Host 'Cleanup Summary'
Write-Host '---------------'
Write-Host ('Scanned files    : {0}' -f $summary.TotalScanned)
Write-Host ('Candidate files  : {0}' -f $summary.CandidateFiles)
Write-Host ('Moved to staging : {0}' -f $summary.MovedToStaging)
Write-Host ('Locked skipped   : {0}' -f $summary.LockedSkipped)
Write-Host ('Failed           : {0}' -f $summary.Failed)
Write-Host ('Dry-run listed   : {0}' -f $summary.DryRunListed)
Write-Host ('Log file         : {0}' -f $logFilePath)

if (-not $DryRun -and $manifestRows.Count -gt 0) {
    Write-Host ('Rollback manifest: {0}' -f $manifestPathForRun)
}

Write-Log -Message ('Script finished. Scanned={0}, Candidates={1}, Moved={2}, Locked={3}, Failed={4}, DryRunListed={5}' -f $summary.TotalScanned, $summary.CandidateFiles, $summary.MovedToStaging, $summary.LockedSkipped, $summary.Failed, $summary.DryRunListed)
